#!/usr/bin/env bash
#
# Setups parse-server, in an easy fashion
# Used for running Test Cases against the parse-php-sdk
#

############
## Config ##
############

# app name
APP_NAME="MyTestApp"

# application id
APP_ID="app-id-here"

# master key
MASTER_KEY="master-key-here"

# mongodb database uri
DATABASE_URI="mongodb://localhost/test"

# location of cloud code file (this location)
CLOUD_CODE_FILE="`pwd`/cloud-code.js"

# parse push configuration (mock and android only)
PUSH_CONFIG='{"android":{"senderId":"blank-sender-id","apiKey":"not-a-real-api-key"}}'

# email adapter configuration, default is mailgun with nonfunctional keys
EMAIL_ADAPTER_CONFIG='{"module":"parse-server-simple-mailgun-adapter","options":{"apiKey":"not-a-real-api-key","domain":"example.com","fromAddress":"example@example.com"}}'

# parse server publicly accessible url
PUBLIC_URL="http://localhost:1337/parse"

# auth data
AUTH_DATA='{"twitter":{"consumer_key":"not_a_real_consumer_key","consumer_secret":"not_a_real_consumer_secret"},"facebook":{"appIds":"not_a_real_facebook_app_id"}}'


# check to update our dependencies before we begin
npm update


# Start MongoDB
mongodb-runner start

# space out commands from mongodb-runner
echo "
"

# Start ParseServer from the command line, note we are using cloud code as well
parse-server\
    --appName $APP_NAME\
    --appId $APP_ID\
    --masterKey $MASTER_KEY\
    --databaseURI $DATABASE_URI\
    --cloud $CLOUD_CODE_FILE\
    --push $PUSH_CONFIG\
    --emailAdapter $EMAIL_ADAPTER_CONFIG\
    --publicServerURL $PUBLIC_URL\
    --auth $AUTH_DATA\
    #--verbose

echo "
...shutting down...
"

# Stop MongoDB
mongodb-runner stop

echo "
Done!
"

exit 0